spring:
  profiles:
    active: prod
  application:
    name: devog-be

  # Devtool Properties
  devtools:
    restart:
      enabled: false

  # Use Docker Postgre Database
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgre
#    username: postgre
#    password: postgre
#    driver-class-name: org.postgresql.Driver

  # Use Local H2 Database
  datasource:
    url: jdbc:h2:mem:devog;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Keys Properties
# Key Must exclude to Commit
keys:
  jjwt: jjwt-token-more-than-32-bit-!@#$%^&*()

jwt:
  expire:
    access: 1800000
    refresh: 2592000000
